version: '3.8'

services:
  # Servidor de tu página Web
  servidor-web:
    build: .
    container_name: devioz-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - base-datos

  # Servidor de tu Base de Datos
  base-datos:
    image: mysql:8.0
    container_name: devioz-db
    environment:
      MYSQL_ROOT_PASSWORD: password_seguro
      MYSQL_DATABASE: devioz_db
      MYSQL_USER: miguel_user
      MYSQL_PASSWORD: miguel_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: